### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by yuler** [yuler/store#1]
- [ ] #34

## apps/mini

- [ ] Move `miniprogram-ci` lazy install

## apps/api

- [ ] Move to sqlite for development
- [ ] Error & Log

## MVP

- [ ] CMS manage products
- [ ] Mini Client order
